=== Herobane/JavaEditor/preferences.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT preferences (window, font)>
<!ELEMENT window (width, height)>
<!ELEMENT width (#PCDATA)>
<!ELEMENT height (#PCDATA)>
<!ELEMENT font (name, style, size)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT style (#PCDATA)>
<!ELEMENT size (#PCDATA)>

=== Herobane/JavaEditor/preferences.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE preferences SYSTEM "preferences.dtd">
<preferences>
	<window>
		<width>780</width>
		<height>540</height>
	</window>
	<font>
		<name>Arial</name>
		<style>3</style>
		<size>32</size>
	</font>
</preferences>
